services:

  ajenti-panel:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: ajenti

    volumes:
      - ./data:/app/data

    ports:
      - "8000:8000"
      - "80:80"

    restart: unless-stopped